"""amber_md/version.py -- single place to render the version banner that gets
stamped into every generated LSF script, so a submitted job's .lsf always
records exactly which code produced it.

Usage in an LSF builder:

    from .version import lsf_banner
    h  = "#!/bin/bash\\n"
    h += lsf_banner("complex_vdw array")   # comment lines, safe in bash
    h += "#BSUB -q ...\\n"

The banner is pure shell comments (lines starting with '#'), so it never
affects execution. It also `echo`-able marker can be emitted at runtime via
runtime_echo() so the version shows up in the job's stdout too.
"""
from __future__ import annotations

import datetime as _dt


def _ver():
    # Imported lazily to avoid any circular import at package init time.
    import amber_md
    v = getattr(amber_md, "__version__", "unknown")
    b = getattr(amber_md, "__build__", "")
    return v, b


def version_string() -> str:
    v, b = _ver()
    return f"amber_md v{v}" + (f" ({b})" if b else "")


def lsf_banner(context: str = "") -> str:
    """Return shell-comment header lines recording the generator version.

    `context` is a free-text tag (e.g. the leg name or script kind) to make
    the banner self-describing in the .lsf file.
    """
    v, b = _ver()
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# ===========================================================",
        f"# Generated by amber_md v{v}" + (f" ({b})" if b else ""),
        f"#   generator   : amber_md.fep / fep_driver",
        f"#   generated_at : {stamp}",
    ]
    if context:
        lines.append(f"#   script       : {context}")
    lines += [
        "#   NOTE: this version line records the EXACT code that wrote this",
        "#   script. If it disagrees with what you expect, the submitting",
        "#   environment is importing a different amber_md install.",
        "# ===========================================================",
    ]
    return "\n".join(lines) + "\n"


def runtime_echo(context: str = "") -> str:
    """Return a bash `echo` line so the version also appears in job stdout."""
    return (f'echo "[amber_md] {version_string()} '
            f'generated this script ({context})"\n')
